name: Bump version
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.11.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: tagBump
      
    - name: Update version in build.gradle
      run: |
         NEW_VERSION=$(echo ${{steps.tagBump.outputs.tag}})
         ./gradlew build && ./gradlew -PcustomV=${NEW_VERSION}
          
    - name: Git Commit and Push
      uses: github-actions-x/commit@v2.4 
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: ${{steps.tagBump.outputs.tag}}
        force-add: 'true'
        files: build.gradle
        
    - name: Publish to GH
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          NEW_VERSION=$(echo ${{steps.tagBump.outputs.tag}})
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          ./gradlew -Pversion=${NEW_VERSION} publish


