name: Bump version
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.11.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
      id: tagBump
    - name: tagInfo
      run: echo "tag ==== ${{steps.tagBump.outputs.tag}}  newtag ==== ${{steps.tagBump.outputs.newTag}}"   


